export const roomData = [
  // Standard Rooms
  {
    id: 1,
    type: "standard",
    name: "Стандартный номер",
    price: 8000,
    capacity: 2,
    description: "Уютный номер с современным дизайном и всеми необходимыми удобствами.",
    image:
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
    amenities: ["Wi-Fi", "Кондиционер", "Телевизор", "Мини-бар", "Сейф"],
  },
  {
    id: 2,
    type: "standard",
    name: "Стандартный номер с видом",
    price: 9000,
    capacity: 2,
    description: "Стандартный номер с прекрасным видом на город и всеми необходимыми удобствами.",
    image:
      "https://images.unsplash.com/photo-1631049035182-249067d7618e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    amenities: ["Wi-Fi", "Кондиционер", "Телевизор", "Мини-бар", "Сейф", "Панорамный вид"],
  },
  {
    id: 3,
    type: "standard",
    name: "Стандартный номер с дополнительной кроватью",
    price: 9500,
    capacity: 3,
    description: "Стандартный номер с дополнительной кроватью, идеально подходит для небольшой семьи.",
    image:
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    amenities: ["Wi-Fi", "Кондиционер", "Телевизор", "Мини-бар", "Сейф", "Дополнительная кровать"],
  },

  // Deluxe Rooms
  {
    id: 4,
    type: "deluxe",
    name: "Делюкс номер",
    price: 12000,
    capacity: 2,
    description: "Просторный номер с элегантным дизайном и дополнительными удобствами для комфортного пребывания.",
    image:
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    amenities: ["Wi-Fi", "Кондиционер", "Телевизор", "Мини-бар", "Сейф", "Халаты и тапочки", "Кофемашина"],
  },
  {
    id: 5,
    type: "deluxe",
    name: "Делюкс номер с балконом",
    price: 14000,
    capacity: 2,
    description: "Роскошный номер с просторным балконом и панорамным видом на город.",
    image:
      "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
    amenities: ["Wi-Fi", "Кондиционер", "Телевизор", "Мини-бар", "Сейф", "Халаты и тапочки", "Кофемашина", "Балкон"],
  },
  {
    id: 6,
    type: "deluxe",
    name: "Делюкс номер с гостиной",
    price: 15000,
    capacity: 3,
    description: "Просторный номер с отдельной гостиной зоной и всеми удобствами для комфортного отдыха.",
    image:
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    amenities: [
      "Wi-Fi",
      "Кондиционер",
      "Телевизор",
      "Мини-бар",
      "Сейф",
      "Халаты и тапочки",
      "Кофемашина",
      "Отдельная гостиная",
    ],
  },

  // Family Rooms
  {
    id: 7,
    type: "family",
    name: "Семейный номер",
    price: 16000,
    capacity: 4,
    description: "Просторный номер, идеально подходящий для семьи с детьми, с двумя спальнями и общей гостиной.",
    image:
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
    amenities: [
      "Wi-Fi",
      "Кондиционер",
      "Телевизор",
      "Мини-бар",
      "Сейф",
      "Две спальни",
      "Гостиная",
      "Детская кроватка по запросу",
    ],
  },
  {
    id: 8,
    type: "family",
    name: "Большой семейный номер",
    price: 18000,
    capacity: 5,
    description: "Просторный номер для большой семьи с двумя спальнями, гостиной и двумя ванными комнатами.",
    image:
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    amenities: [
      "Wi-Fi",
      "Кондиционер",
      "Телевизор",
      "Мини-бар",
      "Сейф",
      "Две спальни",
      "Гостиная",
      "Две ванные комнаты",
      "Детская кроватка по запросу",
    ],
  },
  {
    id: 9,
    type: "family",
    name: "Семейный люкс",
    price: 20000,
    capacity: 6,
    description: "Роскошный семейный люкс с тремя спальнями, просторной гостиной и столовой зоной.",
    image:
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    amenities: [
      "Wi-Fi",
      "Кондиционер",
      "Телевизор",
      "Мини-бар",
      "Сейф",
      "Три спальни",
      "Гостиная",
      "Столовая",
      "Две ванные комнаты",
      "Детская кроватка по запросу",
    ],
  },

  // Presidential Suites
  {
    id: 10,
    type: "presidential",
    name: "Президентский люкс",
    price: 25000,
    capacity: 2,
    description: "Эксклюзивный люкс с изысканным дизайном, отдельной гостиной, столовой и персональным обслуживанием.",
    image:
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    amenities: [
      "Wi-Fi",
      "Кондиционер",
      "Телевизор",
      "Мини-бар",
      "Сейф",
      "Гостиная",
      "Столовая",
      "Джакузи",
      "Персональный дворецкий",
      "Трансфер из/в аэропорт",
    ],
  },
  {
    id: 11,
    type: "presidential",
    name: "Президентский люкс с двумя спальнями",
    price: 30000,
    capacity: 4,
    description:
      "Роскошный люкс с двумя спальнями, просторной гостиной, столовой, джакузи и панорамным видом на город.",
    image:
      "https://images.unsplash.com/photo-1591088398332-8a7791972843?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
    amenities: [
      "Wi-Fi",
      "Кондиционер",
      "Телевизор",
      "Мини-бар",
      "Сейф",
      "Две спальни",
      "Гостиная",
      "Столовая",
      "Джакузи",
      "Персональный дворецкий",
      "Трансфер из/в аэропорт",
    ],
  },
  {
    id: 12,
    type: "presidential",
    name: "Королевский люкс",
    price: 35000,
    capacity: 6,
    description:
      "Самый роскошный номер в отеле с тремя спальнями, гостиной, столовой, сауной, джакузи и террасой с панорамным видом.",
    image:
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    amenities: [
      "Wi-Fi",
      "Кондиционер",
      "Телевизор",
      "Мини-бар",
      "Сейф",
      "Три спальни",
      "Гостиная",
      "Столовая",
      "Сауна",
      "Джакузи",
      "Терраса",
      "Персональный дворецкий",
      "Трансфер из/в аэропорт",
    ],
  },
]
